name: Setup
description: 'Setup stuff'
inputs:
  encryption_key:
    default: ""
    description: "Encryption key for Gradle Configuration Cache"
runs:
  using: "composite"
  steps:
    - name: set up JDK 27
      uses: actions/setup-java@de7274f081f381c8f8158605e0321c36c376e2e6 # v6.0.1
      with:
        distribution: 'zulu'
        java-version: '27'
    - name: Set up jemalloc
      uses: kaeawc/setup-jemalloc@2c377b1a87e4f48c405f69642eb5e82a13ce3987 # v0.1.0
    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@3f5f9adaf7d9fecd50b5935e54106014257a94e6 # v6
      with:
        cache-encryption-key: ${{ inputs.encryption_key }}
