name: Setup
description: 'Setup stuff'
inputs:
  encryption_key:
    default: ""
    description: "Encryption key for Gradle Configuration Cache"
runs:
  using: "composite"
  steps:
    - name: set up JDK 26
      uses: actions/setup-java@de7274f081f381c8f8158605e0321c36c376e2e6 # v6.0.1
      with:
        distribution: 'zulu'
        java-version: '26'
    - name: Set up jemalloc
      uses: kaeawc/setup-jemalloc@a9b92a00f7bc2768fc855b7a235a33043d17492e # v0.0.6
    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@9c971963bec38e04b3d30dcc455b5382be2fdbfb # v6
      with:
        cache-encryption-key: ${{ inputs.encryption_key }}
