[versions]
ksoup = "0.2.6"
kotlin = "2.4.10"
jdkTarget = "17"
coroutines = "1.11.0"
jdk = "26"
eithernet = "2.0.0"

[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
metro = { id = "dev.zacsweers.metro", version = "1.3.2" }
burst = { id = "app.cash.burst" }
convention-jvm = { id = "dev.whosnickdoglio.convention.kotlin", version = "0.4.0" }
detekt = { id = "dev.detekt", version = "2.0.0-alpha.5" }
lint = { id = "com.android.lint", version = "9.3.0" }
doctor = { id = "com.osacky.doctor", version = "0.12.1" }
dependencyAnalysis = { id = "com.autonomousapps.dependency-analysis", version = "3.17.0" }
sortDependencies = { id = "com.squareup.sort-dependencies", version = "0.20.0" }
kover = { id = "org.jetbrains.kotlinx.kover", version = "0.9.9" }
ktfmt = { id = "com.ncorti.ktfmt.gradle", version = "0.26.0" }
mockingbird = { id = "com.anthonycr.plugins.mockingbird", version = "3.3.0" }

[libraries]
ksoup = { module = "com.fleeksoft.ksoup:ksoup", version.ref = "ksoup" }
ksoup-network = { module = "com.fleeksoft.ksoup:ksoup-network", version.ref = "ksoup" }

kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "coroutines" }
kotlinx-coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "coroutines" }
kotlinx-serialization = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version = "1.11.0" }

google-api-client = { module = "com.google.api-client:google-api-client", version = "2.9.0" }
google-sheets = { module = "com.google.apis:google-api-services-sheets", version = "v4-rev20260610-2.0.0" }

retrofit-bom = { module = "com.squareup.retrofit2:retrofit-bom", version = "3.0.0" }
retrofit = { module = "com.squareup.retrofit2:retrofit" }
retrofit-serialization = { module = "com.squareup.retrofit2:converter-kotlinx-serialization" }
okhttp-bom = { module = "com.squareup.okhttp3:okhttp-bom", version = "5.4.0" }
okhttp = { module = "com.squareup.okhttp3:okhttp" }
okhttp-logging = { module = "com.squareup.okhttp3:logging-interceptor" }
eithernet = { module = "com.slack.eithernet:eithernet", version.ref = "eithernet" }
eithernet-retrofit = { module = "com.slack.eithernet:eithernet-integration-retrofit", version.ref = "eithernet" }

# https://www.slf4j.org/codes.html#noProviders
slf4j = { module = "org.slf4j:slf4j-nop", version = "2.0.18" }

junit = { module = "junit:junit", version = "4.13.2" }
burst = { module = "app.cash.burst:burst-gradle-plugin", version = "2.13.0" }
assertk = { module = "com.willowtreeapps.assertk:assertk", version = "0.28.1" }
