[versions]
ksoup = "0.2.5"
kotlin = "2.2.20"
jdk = "24"

[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
metro = { id = "dev.zacsweers.metro", version = "0.7.0" }
burst = { id = "app.cash.burst" }

[libraries]
ksoup = { module = "com.fleeksoft.ksoup:ksoup", version.ref = "ksoup" }
ksoup-network = { module = "com.fleeksoft.ksoup:ksoup-network", version.ref = "ksoup" }

kotlinx-date = { module = "org.jetbrains.kotlinx:kotlinx-datetime", version = "0.7.1" }
kotlinx-serialization = { module = "org.jetbrains.kotlinx:kotlinx-serialization-core", version = "1.9.0" }
kotlinx-serialization-csv = { module = "de.brudaswen.kotlinx.serialization:kotlinx-serialization-csv", version = "2.1.0" }

google-api-client = { module = "com.google.api-client:google-api-client", version = "2.8.1" }
google-ouath = { module = "com.google.oauth-client:google-oauth-client-jetty", version = "1.39.0" }
google-sheets = { module = "com.google.apis:google-api-services-sheets", version = "v4-rev20250616-2.0.0" }

# https://www.slf4j.org/codes.html#noProviders
slf4j = {module = "org.slf4j:slf4j-nop", version = "2.0.17"}

junit = { module = "junit:junit", version = "4.13.2" }
burst = { module = "app.cash.burst:burst-gradle-plugin", version = "2.10.2" }
assertk = { module = "com.willowtreeapps.assertk:assertk", version = "0.28.1" }
