name: Check Rosters
on:
  workflow_dispatch:
  schedule:
    - cron: '0 7 * * *'
jobs:
  Build:
    runs-on: ubuntu-latest
    env:
      GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
    strategy:
      matrix:
        league: [ mitch, redacted, birthday ]
    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
      - uses: ./.github/actions/setup
        with:
          encryption_key: ${{ secrets.GRADLE_ENCRYPTION_KEY }}
      - name: 'Run the script'
        run: ./gradlew data-collector:run  --args="${{ matrix.league }}"
      - name: 'Upload Artifact'
        uses: actions/upload-artifact@v6
        with:
          name: '${{ matrix.league }}_${{ github.run_id }}'
          path: ./data-collector/${{ matrix.league }}_raw_input_${{ github.run_id }}.json
          retention-days: 14
