name: Check Rosters
on:
  workflow_dispatch:
  schedule:
    - cron: '0 7 * * *'
jobs:
  Build:
    runs-on: ubuntu-latest
    env:
      GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
    strategy:
      matrix:
        league: [ mitch, redacted, birthday ]
    steps:
      - uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5.0.1
      - uses: ./.github/actions/setup
        with:
          encryption_key: ${{ secrets.GRADLE_ENCRYPTION_KEY }}
      - name: 'Run the script'
        run: ./gradlew app:run  --args="${{ matrix.league }}"
      - name: 'Upload Artifact'
        uses: actions/upload-artifact@v5
        with:
         name: '${{ matrix.league }}_${{ github.run_id }}'
         path: ./app/${{ matrix.league }}_raw_input_${{ github.run_id }}.json
         retention-days: 14
